name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    environment: employee_attrition

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/employee_attrition-fastapi:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f employee_attrition-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name employee_attrition-fastapi-container $DOCKER_USER/employee_attrition-fastapi:latest

      - name: Install ngrok
        run: |
          curl -sSL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip \
            -o ngrok.zip && unzip ngrok.zip
      
      - name: Run your container
        run: |
          docker run -d -p 8001:8001 --name api employee_attrition-fastapi
      
      - name: Expose via ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_TOKEN
          nohup ./ngrok http 8001 &
      
      - name: Show public URL
        run: curl --silent http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url

